type: google.api.Service
config_version: 3

http:
  rules:
    # Blockchain APIs
    - selector: pactus.Blockchain.GetBlock
      get: "/v1/blockchain/block/height/{height}/verbosity/{verbosity}"

    - selector: pactus.Blockchain.GetBlockHash
      get: "/v1/blockchain/block_hash/{height}"

    - selector: pactus.Blockchain.GetBlockHeight
      get: "/v1/blockchain/block_height/{hash}"

    - selector: pactus.Blockchain.GetAccount
      get: "/v1/blockchain/account/address/{address}"

    - selector: pactus.Blockchain.GetValidators
      get: "/v1/blockchain/validators"

    - selector: pactus.Blockchain.GetValidator
      get: "/v1/blockchain/validator/address/{address}"

    - selector: pactus.Blockchain.GetValidatorByNumber
      get: "/v1/blockchain/validator/{number}"

    - selector: pactus.Blockchain.GetBlockchainInfo
      get: "/v1/blockchain/info"

    # Transaction APIs
    - selector: pactus.Transaction.GetTransaction
      get: "/v1/transaction/id/{id}/verbosity/{verbosity}"

    - selector: pactus.Transaction.SendRawTransaction
      put: "/v1/transaction/send_raw_transaction/{data}"

    # Network APIs
    - selector: pactus.Network.GetNetworkInfo
      get: "/v1/network/info"

    - selector: pactus.Network.GetPeerInfo
      get: "/v1/network/peer_info"

    # Wallet APIs
    - selector: pactus.Wallet.GenerateMnemonic
      get: "/v1/wallet/mnemonic/entropy/{entropy}/language/{language}"

    - selector: pactus.Wallet.CreateWallet
      get: "/v1/wallet/create/name/{name}/mnemonic/{mnemonic}/language/{language}"
